In [ ]:
# Google Driveと接続を行います。これを行うことで、Driveにあるデータにアクセスできるようになります。
# 下記セルを実行すると、Googleアカウントのログインを求められますのでログインしてください。
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 作業フォルダへの移動を行います。
# 人によって作業場所がことなるので、その場合作業場所を変更してください。
import os 
os.chdir('/content/drive/MyDrive/100knock-data_analytics/12章') #ここを変更。

# １２章　データ加工に挑戦する１０本ノック

本章ではデータ加工を扱う10個の課題に挑戦してみましょう。

放課後ノックということで、本編のようなストーリー仕立てではなく入力データと出力データを定義した後は、各自フリーにプログラムでデータ加工を行ってみて下さい。

解答の一例としてサンプルソースを用意していますが、ここまでノックを行ってきた皆様なら、PythonやPandasなどの取り扱いにも十分慣れてきていると思いますので、出来る限り色々ご自身で調べたり、試行錯誤したりしながらトライしてみてください。

### 放課後ノック１１１：”よくある”エクセルデータに挑戦

   都道府県 市区町村  人数（男性、女性）
0   東京都  新宿区         12
1   NaN  NaN         14
2   NaN  豊島区         15
3   NaN  NaN         13
4  神奈川県  横浜市          8

   都道府県  市区町村  男性  女性
0   東京都   新宿区  12  14
1   東京都   豊島区  15  13
2  神奈川県   横浜市   8   9
3  神奈川県  横須賀市   5   2

### 放課後ノック１１２： エクセルの社員マスタ加工に挑戦

      社員名       生年月日  部署   役職        更新日
0    田中 正 1975-10-09  A部   課長 2021-10-12
1  水野 メイサ 1981-02-23  C部   課長 2020-05-08
2    齊藤 隆 2001-01-23  B部  NaN 2021-05-08
3   茂木 新人 2002-08-23  A部  NaN 2021-04-01
4   篠山 雅功 1992-07-02  A部   課長 2022-03-02
5  水野 メイサ 1981-02-23  C部   部長 2021-12-08
6   白鳥 りえ 1999-04-11  B部  NaN 2022-02-01
7    田中 正 1975-10-09  A部   部長 2022-03-02
8   篠山 雅功 1992-07-02  B部  NaN 2021-01-15

### 放課後ノック１１３： 正規化に挑戦

### 放課後ノック１１４： 外れ値の加工に挑戦

### 放課後ノック１１５： 欠損値の補完に挑戦

### 放課後ノック１１６： データのスクランブル化に挑戦

### 放課後ノック１１７： 文字コードの自動判定に挑戦

### 放課後ノック１１８： センサーデータの加工に挑戦

### 放課後ノック１１９： JSON形式に挑戦

### 放課後ノック１２０： SQLiteに挑戦